# Generated by Django 2.1.4 on 2018-12-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.TextField(default='website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
